name: run-simplepy
base: core18
version: '1.0.0'
summary: Simple Py
description: |
  Simple Py
grade: stable
confinement: strict
architectures:
  - build-on: amd64

apps:
  runhello:
     command: /snap/run-simplepy/current/python-bin
     plugs: [home]
  
parts:
  cprog:
    source: https://github.com/drunkenlord/run-simplepy/releases/download/v1.0.0/py.tar.gz
    plugin: dump
