name: run-simp-py
base: core18
version: '1.0.0'
summary: Simple Py
description: |
  Simple Py
grade: stable
confinement: strict
architectures:
  - build-on: amd64

apps:
  python:
    command: python
  runhello:
     command: python

  
parts:
  cprog:
    source: https://github.com/drunkenlord/run-simplepy/releases/download/v1.0.0/py.tar.gz
    plugin: dump

  python:
    plugin: python
    python-version: python2 
    python-packages:
      - argparse==1.2.2
